# Jekyll configuration

name: Sensorberg Developer Hub
description: Your toolbox to develop your own Beacon-based solution!

# url is currently only used only for the RSS feed in feed.xml
url: https://developer.sensorberg.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'sensorberg-dev'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'sensorberg-dev'
comments: true

permalink: /:year/:month/:title/
paginate: 3

latestiOSRelease : "2.5"
latestAndroidSDKRelease : "2.3.3-RAILS"

excerpt_separator: <!--more-->
highlighter: rouge
# markdown: kramdown
# kramdown:
#   input: GFM
gems: [jekyll-paginate, html-proofer]
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE', 'Rakefile', 'Gemfile', 'Gemfile.lock']

collections:
  frontend-releases:
    output: false
    permalink: /frontend-releases/:path/
  videos:
    output: true
    permalink: /videos/:path/
  videos-iframe:
    output: true
    permalink: /videos-iframe/:path/
